### ISSUE TITLE
question reput monster

### ISSUE THREAD

**Issue by skr4w** [JOAOMASTER/OpenNosFamily-master#1]
You added the reputation on the monsters? When you kill them please? I am looking for how to do this because I do not understand

**Comment by Fizo55** [comment]
This is not very complicated ..... Go to opennos.gameobject / character.cs done ctrl + f and mark GetXP after finding the xp system you set Reput + 500 * 2; Inside the functions with the lvl xp

**Comment by skr4w** [comment]
thx you
